#decred-golang-builder-1.7
FROM golang:1.7.6

LABEL description="Decred golang builder image"
LABEL version="1.0"
LABEL maintainer "john@netpurgatory.com"

ENV TERM linux
ENV USER build

# create user
RUN adduser --disabled-password --gecos ''  build

# update base distro & install build tooling
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -qy rsync

# create directory for build artifacts, adjust user permissions
RUN mkdir /release && \
    chown $USER /release

# create directory to get source from
RUN mkdir /src && \
    chown $USER /src && \
    mkdir -p /go/src/github.com/decred/dcrd && \
    mkdir -p /go/src/github.com/decred/dcrwallet && \
    mkdir -p /go/src/github.com/decred/dcrctl && \
    mkdir -p /go/src/github.com/decred/dcrrpcclient && \
    chown -R $USER /go/src/github.com/decred

# switch user
USER $USER
ENV HOME /home/$USER

#Get deps
ENV GLIDE_TAG v0.12.3
ENV GOMETALINTER_TAG v1.2.1

WORKDIR /go/src
RUN go get -v github.com/Masterminds/glide && \
    cd /go/src/github.com/Masterminds/glide && \
    git checkout $GLIDE_TAG && \
    make build && \
    mv glide `which glide` && \
    go get -v github.com/alecthomas/gometalinter && \
    cd /go/src/github.com/alecthomas/gometalinter && \
    git checkout $GOMETALINTER_TAG && \
    go install && \
    gometalinter --install
