package miniscript

import (
	"bufio"
	"encoding/hex"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/btcsuite/btcd/btcec/v2"
	"github.com/btcsuite/btcd/btcec/v2/schnorr"
	"github.com/stretchr/testify/require"
)

// TestDifferentialP2WSH compares the structural properties computed by this Go
// implementation in the P2WSH context against a reference set generated by
// rust-miniscript.
func TestDifferentialP2WSH(t *testing.T) {
	t.Parallel()
	runPropsDifferential(t, "testdata/props_from_rust.tsv", P2WSH)
}

// TestDifferentialP2TR is the same as TestDifferentialP2WSH but for the
// Tapscript context, using multi_a instead of multi and x-only keys.
func TestDifferentialP2TR(t *testing.T) {
	t.Parallel()
	runPropsDifferential(t, "testdata/props_from_rust_tap.tsv", P2TR)
}

// runPropsDifferential reads the given rust-generated property file and asserts
// that Go computes the same properties for every expression in the given
// context. Each row is: expr, script_size, op_count, sat_witness_elements,
// exec_stack, mixed_timelocks, non_malleable, requires_sig.
func runPropsDifferential(t *testing.T, path string, ctx Context) {
	f, err := os.Open(path)
	require.NoError(t, err)
	defer func() {
		require.NoError(t, f.Close())
	}()

	// mismatch counters and a few examples per property, so a systematic
	// error surfaces clearly instead of failing on the first row.
	type mismatch struct {
		expr            string
		property        string
		gotGo, wantRust string
	}
	var mismatches []mismatch
	record := func(expr, prop, got, want string) {
		if len(mismatches) < 40 {
			mismatches = append(mismatches, mismatch{
				expr, prop, got, want,
			})
		}
	}

	counts := map[string]int{}
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)

	// Skip the header.
	require.True(t, scanner.Scan())

	total := 0
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" {
			continue
		}
		fields := strings.Split(line, "\t")
		expr := fields[0]
		total++

		// If rust rejected the expression, Go must reject it too
		// (parse-agreement). This mainly exercises the Tap corpus,
		// where the mechanical multi -> multi_a substitution produces
		// some expressions that do not type-check.
		if len(fields) == 2 && fields[1] == "PARSE_ERR" {
			if _, err := Parse(expr, ctx); err == nil {
				counts["parse_should_fail"]++
				record(expr, "parse", "ok", "PARSE_ERR")
			}
			continue
		}
		require.Lenf(t, fields, 9, "malformed row: %s", line)

		node, err := Parse(expr, ctx)
		if err != nil {
			counts["parse"]++
			record(expr, "parse", err.Error(), "ok")
			continue
		}

		wantScriptSize, _ := strconv.Atoi(fields[1])
		wantOpCount, _ := strconv.Atoi(fields[2])
		wantSatWitness, _ := strconv.Atoi(fields[3])
		wantExecStack, _ := strconv.Atoi(fields[4])
		wantMixed := fields[5] == "true"
		wantNonMalleable := fields[6] == "true"
		wantRequiresSig := fields[7] == "true"
		wantSatSize, _ := strconv.Atoi(fields[8])

		// Script size.
		if node.scriptLen != wantScriptSize {
			counts["script_size"]++
			record(
				expr, "script_size",
				strconv.Itoa(node.scriptLen),
				strconv.Itoa(wantScriptSize),
			)
		}

		// Op count. Rust reports -1 when the expression is
		// unsatisfiable (no satisfaction data).
		if wantOpCount == -1 {
			if node.opCount.sat.valid {
				counts["op_count_sat"]++
				record(
					expr, "op_count(should be unsat)",
					strconv.Itoa(node.maxOpCount()), "-1",
				)
			}
		} else if node.maxOpCount() != wantOpCount {
			counts["op_count"]++
			record(
				expr, "op_count",
				strconv.Itoa(node.maxOpCount()),
				strconv.Itoa(wantOpCount),
			)
		}

		// Satisfaction witness element count (including the witness
		// script, hence +1). Rust reports -1 when unsatisfiable.
		if wantSatWitness == -1 {
			if node.stackSize.sat.valid {
				counts["witness_sat"]++
				record(
					expr, "witness(should be unsat)",
					strconv.Itoa(node.maxWitnessSize()+1),
					"-1",
				)
			}
		} else if node.maxWitnessSize()+1 != wantSatWitness {
			counts["witness"]++
			record(
				expr, "sat_witness_elements",
				strconv.Itoa(node.maxWitnessSize()+1),
				strconv.Itoa(wantSatWitness),
			)
		}

		// Satisfaction witness byte size. Rust reports -1 when
		// unsatisfiable. This also cross-checks the witness element
		// count computed by the same pass against rust's value above.
		gotSatSize, satErr := node.MaxSatisfactionSize()
		gotSatElems, _ := node.MaxSatisfactionWitnessElements()
		if wantSatSize == -1 {
			if satErr == nil {
				counts["sat_size_sat"]++
				record(
					expr, "sat_size(should be unsat)",
					strconv.Itoa(gotSatSize), "-1",
				)
			}
		} else {
			if satErr != nil {
				counts["sat_size_unsat"]++
				record(
					expr, "sat_size(should be sat)",
					"unsat", strconv.Itoa(wantSatSize),
				)
			} else if gotSatSize != wantSatSize {
				counts["sat_size"]++
				record(
					expr, "sat_size",
					strconv.Itoa(gotSatSize),
					strconv.Itoa(wantSatSize),
				)
			}

			// The element count from this pass must agree with the
			// count validated against rust above.
			if satErr == nil && wantSatWitness != -1 &&
				gotSatElems != wantSatWitness {

				counts["sat_size_elems"]++
				record(
					expr, "sat_size_elements",
					strconv.Itoa(gotSatElems),
					strconv.Itoa(wantSatWitness),
				)
			}
		}

		// Note: we deliberately do NOT compare the execution stack size
		// (fields[4]) against rust. For thresholds, rust's
		// max_exec_stack_count is an order-dependent, internally
		// inconsistent conservative estimate (it over-counts the
		// satisfaction via a cumulative accumulator over k+1 sub
		// expressions, whose value depends on the incidental order left
		// by prior in-place field sorts, and under-counts the
		// dissatisfaction with a plain max). Go instead computes the
		// tight, true execution stack peak, which is validated by the
		// hand-computed cases in TestExecStack. The value is only used
		// for the P2TR 1000-element stack limit, which no realistic
		// script approaches.
		_ = wantExecStack

		// Time lock mixing.
		if node.timelock.containsCombination != wantMixed {
			counts["mixed_timelocks"]++
			record(
				expr, "mixed_timelocks",
				strconv.FormatBool(
					node.timelock.containsCombination,
				),
				strconv.FormatBool(wantMixed),
			)
		}

		// Non-malleability (Go props.m).
		if node.props.m != wantNonMalleable {
			counts["non_malleable"]++
			record(
				expr, "non_malleable",
				strconv.FormatBool(node.props.m),
				strconv.FormatBool(wantNonMalleable),
			)
		}

		// Requires signature (Go props.s).
		if node.props.s != wantRequiresSig {
			counts["requires_sig"]++
			record(
				expr, "requires_sig",
				strconv.FormatBool(node.props.s),
				strconv.FormatBool(wantRequiresSig),
			)
		}
	}
	require.NoError(t, scanner.Err())

	t.Logf("compared %d %v expressions against rust-miniscript", total,
		ctx)

	if len(counts) > 0 {
		t.Logf("mismatch counts by property: %v", counts)
		for _, m := range mismatches {
			t.Logf("MISMATCH [%s] expr=%s go=%s rust=%s",
				m.property, m.expr, m.gotGo, m.wantRust)
		}
		t.Fatalf("found mismatches vs rust-miniscript: %v", counts)
	}
}

// TestDifferentialScriptHexP2WSH compares the actual witness script bytes
// generated by this Go implementation against rust-miniscript's encode() output
// in the P2WSH context. The reference file maps each expression (using the
// single-letter key placeholders A..Z) to the hex of the script rust generates
// when each letter is substituted by the public key derived from the secret key
// whose only nonzero byte is its 1-based index (A=1, B=2, ...). Go derives the
// same keys, so the scripts must match byte for byte.
func TestDifferentialScriptHexP2WSH(t *testing.T) {
	t.Parallel()
	runScriptDifferential(t, "testdata/scripts_from_rust.tsv", P2WSH)
}

// TestDifferentialScriptHexP2TR is the same as TestDifferentialScriptHexP2WSH
// but for the Tapscript context, using x-only keys and multi_a.
func TestDifferentialScriptHexP2TR(t *testing.T) {
	t.Parallel()
	runScriptDifferential(t, "testdata/scripts_from_rust_tap.tsv", P2TR)
}

// runScriptDifferential compares Go's generated script bytes against the
// rust-generated reference for every expression in the given context. Keys A..Z
// map to the compressed (P2WSH) or x-only (P2TR) public key of the secret key
// whose only nonzero byte is its 1-based index.
func runScriptDifferential(t *testing.T, path string, ctx Context) {
	// Build the same A..Z -> pubkey map rust uses for this context.
	pubKeys := map[string][]byte{}
	for i := 1; i <= 26; i++ {
		var b [32]byte
		b[31] = byte(i)
		priv, pub := btcec.PrivKeyFromBytes(b[:])
		key := pub.SerializeCompressed()
		if ctx == P2TR {
			key = schnorr.SerializePubKey(priv.PubKey())
		}
		pubKeys[string(rune('A'+i-1))] = key
	}
	lookupVar := func(identifier string) ([]byte, error) {
		if pk, ok := pubKeys[identifier]; ok {
			return pk, nil
		}

		// Not a key placeholder: let ApplyVars decode it as hex (hash
		// values).
		return nil, nil
	}

	f, err := os.Open(path)
	require.NoError(t, err)
	defer f.Close()

	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)

	total, compared, skipped, mismatches := 0, 0, 0, 0
	var examples []string
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" {
			continue
		}
		fields := strings.SplitN(line, "\t", 2)
		require.Lenf(t, fields, 2, "malformed row: %s", line)
		expr, wantHex := fields[0], fields[1]
		total++

		if wantHex == "ERR" {
			continue
		}

		node, err := Parse(expr, ctx)
		require.NoErrorf(t, err, "go could not parse %s", expr)

		// Duplicate-key detection is a Go-specific feature that rust's
		// from_str_insane does not perform; skip those expressions for
		// the pure script-encoding comparison.
		if err := node.ApplyVars(lookupVar); err != nil {
			if strings.Contains(err.Error(), "duplicate key") {
				skipped++
				continue
			}
			t.Fatalf("applyvars %s: %v", expr, err)
		}

		script, err := node.Script()
		require.NoErrorf(t, err, "go could not build script for %s",
			expr)

		gotHex := hex.EncodeToString(script)
		compared++
		if gotHex != wantHex {
			mismatches++
			if len(examples) < 30 {
				examples = append(examples, expr)
				t.Logf("SCRIPT MISMATCH %s\n  go=  %s\n  "+
					"rust=%s", expr, gotHex, wantHex)
			}
		}
	}
	require.NoError(t, scanner.Err())

	t.Logf("script hex: total=%d compared=%d skipped(dup keys)=%d "+
		"mismatches=%d", total, compared, skipped, mismatches)
	require.Zerof(t, mismatches, "found %d script hex mismatches vs "+
		"rust-miniscript", mismatches)
}
