package frost

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"slices"

	"github.com/btcsuite/btcd/btcec/v2"
	"github.com/btcsuite/btcd/btcec/v2/schnorr"
	"github.com/btcsuite/btcd/btcec/v2/schnorr/threshold/util"
	"github.com/btcsuite/btcd/chainhash/v2"
)

// MAX_PARTICIPANTS is the upper bound on the total number of participants n.
// See the footnote on this bound in the BIP text for the security rationale.
const MAX_PARTICIPANTS = 128

var bigEndian = binary.BigEndian

func hasDuplicates(ids []int) bool {
	mapIds := make(map[int]struct{})

	for i := range ids {
		mapIds[ids[i]] = struct{}{}
	}

	return len(mapIds) != len(ids)
}

func DerivePubShareAt(ids []int, pubShares []*btcec.PublicKey, x int) (
	*btcec.PublicKey, error) {

	if len(ids) != len(pubShares) {
		return nil, fmt.Errorf("lists of ids and pubshares must be " +
			"same length")
	}
	if hasDuplicates(ids) {
		return nil, fmt.Errorf("The ids list contains duplicate " +
			"elements.")
	}

	var (
		num     = new(btcec.ModNScalar)
		deno    = new(btcec.ModNScalar)
		numMul  = new(btcec.ModNScalar)
		denoMul = new(btcec.ModNScalar)
		idNeg   = new(btcec.ModNScalar)
		q       = new(btcec.JacobianPoint)
		xi      = new(btcec.JacobianPoint)
	)

	for i := range ids {
		idNeg.SetInt(uint32(ids[i]))
		idNeg.Negate()

		num.SetInt(uint32(1))
		deno.SetInt(uint32(1))
		pubShares[i].AsJacobian(xi)

		for j := range ids {
			if ids[i] == ids[j] {
				continue
			}

			numMul.SetInt(uint32(ids[j] + 1))
			denoMul.SetInt(uint32(ids[j]))
			denoMul.Add(idNeg)

			num.Mul(numMul)
			deno.Mul(denoMul)
		}

		deno.InverseNonConst()
		num.Mul(deno)
		btcec.ScalarMultNonConst(num, xi, xi)
		btcec.AddNonConst(q, xi, q)
	}

	q.ToAffine()

	return btcec.NewPublicKey(&q.X, &q.Y), nil
}

func DeriveThresholdPubKey(ids []int, pubShares []*btcec.PublicKey) (
	*btcec.PublicKey, error) {

	q, err := DerivePubShareAt(ids, pubShares, -1)
	if err != nil {
		return nil, err
	}

	if util.IsPubKeyAtInfinity(q) {
		return nil, fmt.Errorf("The threshold public key must not be " +
			"the point at infinity.")
	}

	return q, nil
}

// ThresholdInfo describes the output of the DKG ceremony.
type ThresholdInfo struct {
	// T is the threshold of cosigners required to sign successfully.
	T int

	// ThresholdPubKey is the public key generated by the DKG ceremony.
	ThresholdPubKey *btcec.PublicKey

	// PubShares is a list of optional public shares. A nil value means the
	// share is unknown to the current participant, such as in the case of
	// data loss. The length of the list is equal to the N parameter, or
	// the number of total participants in the DKG ceremony.
	PubShares []*btcec.PublicKey
}

func ValidateThresholdInfo(info *ThresholdInfo) error {
	n := len(info.PubShares)

	if info.T < 1 || info.T > n {
		return fmt.Errorf("The threshold must be 1 <= t <= n.")
	}

	if n > MAX_PARTICIPANTS {
		return fmt.Errorf("The number of participants must be n <= %d.",
			MAX_PARTICIPANTS)
	}

	var (
		ids       []int
		pubShares []*btcec.PublicKey
	)

	for i, pubShare := range info.PubShares {
		if pubShare != nil {
			ids = append(ids, i)
			pubShares = append(pubShares, pubShare)
		}
	}

	if len(pubShares) < info.T {
		return fmt.Errorf("At least t pubshares must be present.")
	}

	baseIds := ids[:info.T]
	basePoints := pubShares[:info.T]

	for i := range ids {
		pubShare, err := DerivePubShareAt(baseIds, basePoints, ids[i])
		if err != nil {
			return err
		}
		if !pubShare.IsEqual(pubShares[i]) {
			return fmt.Errorf("The provided key material is " +
				"incorrect: the public shares do not lie on " +
				"a single polynomial.",
			)
		}
	}

	threshPk, err := DeriveThresholdPubKey(baseIds, basePoints)
	if err != nil {
		return err
	}
	if !threshPk.IsEqual(info.ThresholdPubKey) {
		return fmt.Errorf("The provided key material is incorrect: " +
			"the public shares do not match the threshold " +
			"public key.",
		)
	}

	return nil
}

type TweakContext struct {
	Q    *btcec.JacobianPoint
	Gacc *btcec.ModNScalar
	Tacc *btcec.ModNScalar
}

func TweakCtxInit(pubkey *btcec.PublicKey) *TweakContext {
	tCtx := &TweakContext{
		Q:    new(btcec.JacobianPoint),
		Gacc: new(btcec.ModNScalar),
		Tacc: new(btcec.ModNScalar),
	}

	pubkey.AsJacobian(tCtx.Q)
	tCtx.Gacc.SetInt(1)
	tCtx.Tacc.SetInt(0)

	return tCtx
}

func ApplyTweak(tCtx *TweakContext, tweak [32]byte, isXonly bool) (
	*TweakContext, error) {

	var (
		q     = new(btcec.JacobianPoint)
		twkPt = new(btcec.JacobianPoint)
		g     = new(btcec.ModNScalar)
		gAcc  = new(btcec.ModNScalar)
		tAcc  = new(btcec.ModNScalar)
		twk   = new(btcec.ModNScalar)
	)

	q.Set(tCtx.Q)
	gAcc.Set(tCtx.Gacc)
	tAcc.Set(tCtx.Tacc)
	g.SetInt(1)

	if isXonly && q.Y.IsOdd() {
		g.Negate()
	}

	overflow := twk.SetBytes(&tweak)
	if overflow != 0 {
		return nil, fmt.Errorf("The tweak value is out of range.")
	}

	btcec.ScalarBaseMultNonConst(twk, twkPt)
	btcec.ScalarMultNonConst(g, q, q)
	btcec.AddNonConst(q, twkPt, q)
	q.ToAffine()

	if util.IsPointAtInfinity(q) {
		return nil, fmt.Errorf("The result of tweaking cannot be " +
			"infinity.")
	}

	gAcc.Mul(g)

	tAcc.Mul(g).Add(twk)

	return &TweakContext{
		Q:    q,
		Gacc: gAcc,
		Tacc: tAcc,
	}, nil
}

func ThresholdPubKeyAndTweak(thresholdPubKey *btcec.PublicKey,
	tweaks [][32]byte, isXonly []bool) (*TweakContext, error) {

	if len(tweaks) != len(isXonly) {
		return nil, fmt.Errorf("The tweaks and is_xonly arrays must " +
			"have the same length.")
	}

	var (
		tCtx = TweakCtxInit(thresholdPubKey)
		err  error
	)
	for i := range tweaks {
		tCtx, err = ApplyTweak(tCtx, tweaks[i], isXonly[i])
		if err != nil {
			return nil, err
		}
	}

	return tCtx, nil
}

func nonceHash(random, pubShare, thresholdPubKey []byte, i int,
	msgPrefixed []byte, extraIn []byte) *chainhash.Hash {

	var buf []byte
	buf = append(buf, random...)
	buf = append(buf, byte(len(pubShare)))
	buf = append(buf, pubShare...)
	buf = append(buf, byte(len(thresholdPubKey)))
	buf = append(buf, thresholdPubKey...)
	buf = append(buf, msgPrefixed...)
	buf = bigEndian.AppendUint32(buf, uint32(len(extraIn)))
	buf = append(buf, extraIn...)
	buf = append(buf, byte(i))
	return chainhash.TaggedHash([]byte("BIP0445/nonce"), buf)
}

type SecretNonce struct {
	Nonce1 *btcec.PrivateKey
	Nonce2 *btcec.PrivateKey
}

func ParseSecretNonce(b []byte) (*SecretNonce, error) {
	if len(b) != 64 {
		return nil, fmt.Errorf("Invalid secret nonce length")
	}

	var (
		n   = new(SecretNonce)
		err error
	)

	n.Nonce1, err = util.ParsePrivKeyNonZeroChecked(b[:32])
	if err != nil {
		return nil, fmt.Errorf("first secnonce value is out of range.")
	}

	n.Nonce2, err = util.ParsePrivKeyNonZeroChecked(b[32:])
	if err != nil {
		return nil, fmt.Errorf("second secnonce value is out of range.")
	}

	return n, nil
}

func (n *SecretNonce) Bytes() []byte {
	return append(
		n.Nonce1.Serialize(),
		n.Nonce2.Serialize()...,
	)
}

func (n *SecretNonce) PubNonce() *PublicNonce {
	return &PublicNonce{
		Nonce1: n.Nonce1.PubKey(),
		Nonce2: n.Nonce2.PubKey(),
	}
}

type PublicNonce struct {
	Nonce1 *btcec.PublicKey
	Nonce2 *btcec.PublicKey
}

func ParsePublicNonce(b []byte) (*PublicNonce, error) {
	if len(b) != 2*33 {
		return nil, fmt.Errorf("Invalid public nonce length")
	}

	var (
		n   = new(PublicNonce)
		err error
	)

	n.Nonce1, err = btcec.ParsePubKey(b[:33])
	if err != nil {
		return nil, err
	}

	n.Nonce2, err = btcec.ParsePubKey(b[33:])
	if err != nil {
		return nil, err
	}

	return n, nil
}

func ParseAggNonce(b []byte) (*PublicNonce, error) {
	if len(b) != 2*33 {
		return nil, ErrInvalidContribution{-1, ContributionTypeAggNonce}
	}

	var (
		n   = new(PublicNonce)
		err error
	)

	n.Nonce1, err = util.ParsePubKeyWithInfinity(b[:33])
	if err != nil {
		return nil, ErrInvalidContribution{-1, ContributionTypeAggNonce}
	}

	n.Nonce2, err = util.ParsePubKeyWithInfinity(b[33:])
	if err != nil {
		return nil, ErrInvalidContribution{-1, ContributionTypeAggNonce}
	}

	return n, nil
}

func (n *PublicNonce) Bytes() []byte {
	return append(
		util.SerializeCompressedWithInfinity(n.Nonce1),
		util.SerializeCompressedWithInfinity(n.Nonce2)...,
	)
}

func nonceGen(random [32]byte, secShare *btcec.PrivateKey,
	thresholdPubKey *btcec.PublicKey, msg *[]byte, extraIn []byte) (
	*SecretNonce, error) {

	var pubShareBytes []byte
	//TODO(aakselrod): separate handling of pubshare
	//TODO(aakselrod): zero secret data
	if secShare != nil {
		secShareBytes := secShare.Serialize()
		randHash := chainhash.TaggedHash([]byte("BIP0445/aux"), random[:])
		for i := range secShareBytes {
			random[i] = randHash[i] ^ secShareBytes[i]
		}
		pubShareBytes = secShare.PubKey().SerializeCompressed()
	}

	var thresholdPubKeyBytes []byte
	if thresholdPubKey != nil {
		thresholdPubKeyBytes = schnorr.SerializePubKey(thresholdPubKey)
	}

	var msgPrefixed []byte
	if msg == nil {
		msgPrefixed = []byte{0}
	} else {
		msgPrefixed = []byte{1}
		msgPrefixed = bigEndian.AppendUint64(
			msgPrefixed, uint64(len(*msg)),
		)
		msgPrefixed = append(msgPrefixed, *msg...)
	}

	k1, k1Pub := btcec.PrivKeyFromBytes(nonceHash(
		random[:], pubShareBytes, thresholdPubKeyBytes, 0, msgPrefixed,
		extraIn,
	)[:])

	k2, k2Pub := btcec.PrivKeyFromBytes(nonceHash(
		random[:], pubShareBytes, thresholdPubKeyBytes, 1, msgPrefixed,
		extraIn,
	)[:])

	if k1.Key.IsZero() || k2.Key.IsZero() {
		return nil, fmt.Errorf("resulting secnonces cannot be " +
			"zero")
	}

	if util.IsPubKeyAtInfinity(k1Pub) || util.IsPubKeyAtInfinity(k2Pub) {
		return nil, fmt.Errorf("resulting pubnonces cannot be " +
			"point at infinity")
	}

	return &SecretNonce{
		Nonce1: k1,
		Nonce2: k2,
	}, nil
}

func NonceGen(secShare *btcec.PrivateKey, thresholdPubKey *btcec.PublicKey,
	msg *[]byte, extraIn []byte) (*SecretNonce, error) {

	random, err := Rand32Int()
	if err != nil {
		return nil, err
	}

	//TODO(aakselrod): pass pointer and zero random
	return nonceGen(*random, secShare, thresholdPubKey, msg, extraIn)
}

func Rand32Int() (*[32]byte, error) {
	var random [32]byte
	l, err := rand.Read(random[:])
	if err != nil {
		return nil, err
	}
	if l != 32 {
		return nil, fmt.Errorf("randomization error")
	}

	return &random, nil
}

func NonceAgg(pubNonces []*PublicNonce) *PublicNonce {
	var (
		p1  = new(btcec.JacobianPoint)
		p2  = new(btcec.JacobianPoint)
		ap1 = new(btcec.JacobianPoint)
		ap2 = new(btcec.JacobianPoint)
	)

	for _, nonce := range pubNonces {
		nonce.Nonce1.AsJacobian(ap1)
		nonce.Nonce2.AsJacobian(ap2)
		btcec.AddNonConst(p1, ap1, p1)
		btcec.AddNonConst(p2, ap2, p2)
	}

	p1.ToAffine()
	p2.ToAffine()

	return &PublicNonce{
		Nonce1: btcec.NewPublicKey(&p1.X, &p1.Y),
		Nonce2: btcec.NewPublicKey(&p2.X, &p2.Y),
	}
}

type SessionContext struct {
	N               int
	T               int
	Ids             []int
	PubShares       []*btcec.PublicKey
	ThresholdPubKey *btcec.PublicKey
	AggNonce        *PublicNonce
	Tweaks          [][32]byte
	IsXOnly         []bool
	Msg             []byte
}

func ValidateSessionParams(n, t int, ids []int, pubShares []*btcec.PublicKey,
	thresholdPubKey *btcec.PublicKey) error {

	if t < 1 || t > n {
		return fmt.Errorf("The threshold must be 1 <= t <= n.")
	}

	if n > MAX_PARTICIPANTS {
		return fmt.Errorf("The number of participants must be n <= %d.",
			MAX_PARTICIPANTS)
	}

	if len(ids) < t || len(ids) > n {
		return fmt.Errorf("The number of signers must be between t " +
			"and n.")
	}

	if len(pubShares) != 0 && len(pubShares) != len(ids) {
		return fmt.Errorf("The pubshares and ids lists must have " +
			"the same length.")
	}

	for idx, i := range ids {
		if i < 0 || i >= n {
			return fmt.Errorf("Invalid id at index %d", idx)
		}

	}

	if len(pubShares) != 0 {
		threshPk, err := DeriveThresholdPubKey(ids, pubShares)
		if err != nil {
			return err
		}
		if !threshPk.IsEqual(thresholdPubKey) {
			return fmt.Errorf("The provided key material is " +
				"incorrect: the public shares do not match " +
				"the threshold public key.")
		}
	}

	return nil
}

func serializeIds(ids []int) []byte {
	idCopy := slices.Clone(ids)
	slices.Sort(idCopy)
	b := make([]byte, 0, 4+len(ids)*4)

	b = bigEndian.AppendUint32(b, uint32(len(ids)))

	for _, id := range idCopy {
		b = bigEndian.AppendUint32(b, uint32(id))
	}

	return b
}

func GetSessionValues(sessionCtx *SessionContext) (*btcec.JacobianPoint,
	*btcec.ModNScalar, *btcec.ModNScalar, []int, []*btcec.PublicKey,
	*btcec.ModNScalar, *btcec.JacobianPoint, *btcec.ModNScalar, error) {

	err := ValidateSessionParams(
		sessionCtx.N, sessionCtx.T, sessionCtx.Ids,
		sessionCtx.PubShares, sessionCtx.ThresholdPubKey,
	)
	if err != nil {
		return nil, nil, nil, nil, nil, nil, nil, nil, err
	}

	tweakCtx, err := ThresholdPubKeyAndTweak(
		sessionCtx.ThresholdPubKey, sessionCtx.Tweaks,
		sessionCtx.IsXOnly,
	)
	if err != nil {
		return nil, nil, nil, nil, nil, nil, nil, nil, err
	}

	hashData := append(
		serializeIds(sessionCtx.Ids),
		sessionCtx.AggNonce.Bytes()...,
	)
	hashData = append(
		hashData,
		schnorr.SerializePubKey(util.GetXOnlyPubKey(tweakCtx.Q))...,
	)
	hashData = append(hashData, sessionCtx.Msg...)

	bBytes := chainhash.TaggedHash([]byte("BIP0445/noncecoef"), hashData)
	b := new(btcec.ModNScalar)
	b.SetBytes((*[32]byte)(bBytes))
	if b.IsZero() {
		return nil, nil, nil, nil, nil, nil, nil, nil,
			fmt.Errorf("resulting b cannot be 0")
	}

	var (
		R1 = new(btcec.JacobianPoint)
		R2 = new(btcec.JacobianPoint)
		R  = new(btcec.JacobianPoint)
	)

	sessionCtx.AggNonce.Nonce1.AsJacobian(R1)
	sessionCtx.AggNonce.Nonce2.AsJacobian(R2)
	btcec.ScalarMultNonConst(b, R2, R)
	btcec.AddNonConst(R, R1, R)

	if util.IsPointAtInfinity(R) {
		// Set R to G
		one := new(btcec.ModNScalar)
		one.SetInt(uint32(1))
		btcec.ScalarBaseMultNonConst(one, R)
	}

	R.ToAffine()

	if util.IsPointAtInfinity(R) {
		return nil, nil, nil, nil, nil, nil, nil, nil,
			fmt.Errorf("resulting R cannot be point at infinity")
	}

	hashData = append(
		schnorr.SerializePubKey(util.GetXOnlyPubKey(R)),
		schnorr.SerializePubKey(util.GetXOnlyPubKey(tweakCtx.Q))...,
	)
	hashData = append(hashData, sessionCtx.Msg...)

	eBytes := chainhash.TaggedHash(chainhash.TagBIP0340Challenge, hashData)
	e := new(btcec.ModNScalar)
	e.SetBytes((*[32]byte)(eBytes))
	if e.IsZero() {
		return nil, nil, nil, nil, nil, nil, nil, nil,
			fmt.Errorf("resulting e cannot be 0")
	}

	return tweakCtx.Q, tweakCtx.Gacc, tweakCtx.Tacc, sessionCtx.Ids,
		sessionCtx.PubShares, b, R, e, nil
}

func Sign(secNonce *SecretNonce, secShare *btcec.PrivateKey, myId int,
	sessionCtx *SessionContext, clearNonce func() error) (
	*btcec.ModNScalar, error) {

	Q, gAcc, _, ids, pubShares, b, R, e, err := GetSessionValues(
		sessionCtx,
	)
	if err != nil {
		return nil, err
	}

	g := new(btcec.ModNScalar)
	g.SetInt(uint32(1))
	if R.Y.IsOdd() {
		g.Negate()
	}

	k1 := new(btcec.ModNScalar)
	k1.Set(&secNonce.Nonce1.Key)
	k1.Mul(g)

	defer k1.Zero()

	k2 := new(btcec.ModNScalar)
	k2.Set(&secNonce.Nonce2.Key)
	k2.Mul(g)

	defer k2.Zero()

	// Clear secNonce
	pubNonce := secNonce.PubNonce()
	secNonce.Nonce1.Zero()
	secNonce.Nonce2.Zero()

	// Clear secNonce in persistent storage using callback
	err = clearNonce()
	if err != nil {
		return nil, err
	}

	myPubShare := secShare.PubKey()
	found := false
	for _, pubShare := range pubShares {
		if myPubShare.IsEqual(pubShare) {
			found = true
			break
		}
	}
	if len(pubShares) != 0 && !found {
		return nil, fmt.Errorf("The signer's pubshare is missing " +
			"from the pubshares list.")
	}

	if !slices.Contains(ids, myId) {
		return nil, fmt.Errorf("The signer's id is missing from the " +
			"ids list.")
	}

	a, err := util.DeriveInterpolatingValue(ids, myId)
	if err != nil {
		return nil, err
	}

	g.SetInt(uint32(1))
	if Q.Y.IsOdd() {
		g.Negate()
	}

	s := new(btcec.ModNScalar)

	// d
	s.Mul2(g, &secShare.Key).Mul(gAcc)

	// e * a * d
	s.Mul(e).Mul(a)

	// + k1
	s.Add(k1)

	// + k2 * b
	s.Add(k2.Mul(b))

	if !partialSigVerify(
		s, myId, pubNonce, secShare.PubKey(), sessionCtx,
	) {
		return nil, fmt.Errorf("signature doesn't match")
	}

	return s, nil
}

func partialSigVerify(pSig *btcec.ModNScalar, myId int,
	pubNonce *PublicNonce, pubShare *btcec.PublicKey,
	sessionCtx *SessionContext) bool {

	Q, gAcc, _, ids, _, b, R, e, err := GetSessionValues(sessionCtx)
	if err != nil {
		return false
	}

	a, err := util.DeriveInterpolatingValue(ids, myId)
	if err != nil {
		return false
	}

	var (
		R1Partial = new(btcec.JacobianPoint)
		R2Partial = new(btcec.JacobianPoint)
		Res       = new(btcec.JacobianPoint)
		P         = new(btcec.JacobianPoint)
		sG        = new(btcec.JacobianPoint)
		g         = new(btcec.ModNScalar)
	)

	btcec.ScalarBaseMultNonConst(pSig, sG)
	sG.ToAffine()

	pubNonce.Nonce1.AsJacobian(R1Partial)
	pubNonce.Nonce2.AsJacobian(R2Partial)
	btcec.ScalarMultNonConst(b, R2Partial, Res)
	btcec.AddNonConst(R1Partial, Res, Res)
	g.SetInt(uint32(1))
	if R.Y.IsOdd() {
		g.Negate()
	}
	btcec.ScalarMultNonConst(g, Res, Res)

	g.SetInt(uint32(1))
	if Q.Y.IsOdd() {
		g.Negate()
	}

	pubShare.AsJacobian(P)
	btcec.ScalarMultNonConst(g, P, P)
	btcec.ScalarMultNonConst(gAcc, P, P)
	btcec.ScalarMultNonConst(e, P, P)
	btcec.ScalarMultNonConst(a, P, P)
	btcec.AddNonConst(Res, P, P)
	P.ToAffine()

	return P.X.Equals(&sG.X) && P.Y.Equals(&sG.Y) && P.Z.Equals(&sG.Z)
}

func PartialSigVerify(pSig *btcec.ModNScalar, pubNonces []*PublicNonce,
	n, t int, ids []int, pubShares []*btcec.PublicKey,
	thresholdPubKey *btcec.PublicKey, tweaks [][32]byte, isXOnly []bool,
	msg []byte, idx int) bool {

	if len(pubNonces) != len(ids) || len(pubShares) != len(ids) {
		return false
	}

	if idx < 0 || idx >= len(ids) {
		return false
	}

	if len(tweaks) != len(isXOnly) {
		return false
	}

	err := ValidateSessionParams(n, t, ids, pubShares, thresholdPubKey)
	if err != nil {
		return false
	}

	sessionCtx := &SessionContext{
		N:               n,
		T:               t,
		Ids:             ids,
		PubShares:       pubShares,
		ThresholdPubKey: thresholdPubKey,
		AggNonce:        NonceAgg(pubNonces),
		Tweaks:          tweaks,
		IsXOnly:         isXOnly,
		Msg:             msg,
	}

	return partialSigVerify(
		pSig, ids[idx], pubNonces[idx], pubShares[idx], sessionCtx,
	)
}

func PartialSigAgg(pSigs []*btcec.ModNScalar, sessionCtx *SessionContext) (
	*schnorr.Signature, error) {

	Q, _, tAcc, ids, _, _, R, e, err := GetSessionValues(
		sessionCtx,
	)
	if err != nil {
		return nil, err
	}
	if len(pSigs) != len(ids) {
		return nil, fmt.Errorf("The psigs and ids lists must have " +
			"the same length.")
	}

	s := new(btcec.ModNScalar)

	for _, pSig := range pSigs {
		s.Add(pSig)
	}

	g := new(btcec.ModNScalar)
	g.SetInt(uint32(1))
	if Q.Y.IsOdd() {
		g.Negate()
	}
	s.Add(g.Mul(e).Mul(tAcc))

	return schnorr.NewSignature(&R.X, s), nil
}

func detNonceHash(secShareBytes []byte, myId int, ids []int,
	aggOtherNonce, tweakedThreshPkXOnly, msg []byte,
	i int) *chainhash.Hash {

	buf := binary.BigEndian.AppendUint32(secShareBytes, uint32(myId))
	buf = append(buf, serializeIds(ids)...)
	buf = append(buf, aggOtherNonce...)
	buf = append(buf, tweakedThreshPkXOnly...)
	buf = bigEndian.AppendUint64(buf, uint64(len(msg)))
	buf = append(buf, msg...)
	buf = append(buf, byte(i))
	defer zeroSlice(buf)
	return chainhash.TaggedHash([]byte("BIP0445/deterministic/nonce"), buf)
}

func DeterministicSign(secShare *btcec.PrivateKey, myId int,
	aggOtherNonce *PublicNonce, n, t int, ids []int,
	pubShares []*btcec.PublicKey, thresholdPubKey *btcec.PublicKey,
	tweaks [][32]byte, isXOnly []bool, msg []byte, auxRand []byte,
) (*PublicNonce, *btcec.ModNScalar, error) {

	err := ValidateSessionParams(n, t, ids, pubShares, thresholdPubKey)
	if err != nil {
		return nil, nil, err
	}

	tweakCtx, err := ThresholdPubKeyAndTweak(
		thresholdPubKey, tweaks, isXOnly,
	)
	if err != nil {
		return nil, nil, err
	}

	tweakedThreshPkXOnly := schnorr.SerializePubKey(
		util.GetXOnlyPubKey(tweakCtx.Q),
	)

	secShareBytes := secShare.Serialize()
	defer zeroSlice(secShareBytes)

	if len(auxRand) != 0 {
		randHash := chainhash.TaggedHash(
			[]byte("BIP0445/aux"), auxRand,
		)
		defer zeroSlice(randHash[:])

		for i, b := range randHash[:] {
			secShareBytes[i] = secShareBytes[i] ^ b
		}
	}

	var aggOtherNonceBytes []byte
	if aggOtherNonce != nil {
		aggOtherNonceBytes = aggOtherNonce.Bytes()
	}

	k1 := detNonceHash(
		secShareBytes, myId, ids, aggOtherNonceBytes,
		tweakedThreshPkXOnly, msg, 0,
	)
	defer zeroSlice(k1[:])

	k2 := detNonceHash(
		secShareBytes, myId, ids, aggOtherNonceBytes,
		tweakedThreshPkXOnly, msg, 1,
	)
	defer zeroSlice(k2[:])

	secNonce := new(SecretNonce)
	secNonce.Nonce1, _ = btcec.PrivKeyFromBytes(k1[:])
	secNonce.Nonce2, _ = btcec.PrivKeyFromBytes(k2[:])

	pubNonce := secNonce.PubNonce()

	aggNonce := secNonce.PubNonce()
	if aggOtherNonce != nil {
		aggNonce = NonceAgg([]*PublicNonce{aggNonce, aggOtherNonce})
	}

	sessionCtx := &SessionContext{
		N:               n,
		T:               t,
		Ids:             ids,
		PubShares:       pubShares,
		ThresholdPubKey: thresholdPubKey,
		AggNonce:        aggNonce,
		Tweaks:          tweaks,
		IsXOnly:         isXOnly,
		Msg:             msg,
	}

	pSig, err := Sign(
		secNonce, secShare, myId, sessionCtx,

		// The Sign() function clears the secret nonce in memory. The
		// callback doesn't need to do anything since the deterministic
		// nonce is never persisted.
		func() error {
			return nil
		},
	)
	if err != nil {
		return nil, nil, err
	}

	return pubNonce, pSig, nil
}

func zeroSlice(buf []byte) {
	for i := range buf {
		buf[i] = 0x00
	}
}
