package descriptors

import (
	"bufio"
	"encoding/hex"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/btcsuite/btcd/chaincfg/v2"
	"github.com/stretchr/testify/require"
)

// descRecords holds the rust-generated reference records for one descriptor.
type descRecords struct {
	str     string
	mplen   string
	typ     string
	mweight string
	lift    string
	plan    []string
	keys    []string
	addr    [][]string
	scode   [][]string
}

// TestDescriptorDifferential compares this Go implementation against the
// rust-miniscript reference for every descriptor in the corpus, on the
// canonical string, multipath length, type, keys, and every derived address and
// script code. The reference is generated by
// code-ingest/rust-miniscript/examples/extract_descriptor.rs into
// testdata/descriptors_from_rust.tsv.
func TestDescriptorDifferential(t *testing.T) {
	t.Parallel()

	f, err := os.Open("testdata/descriptors_from_rust.tsv")
	require.NoError(t, err)
	defer f.Close()

	// Read and group the reference records by descriptor, preserving order
	// of appearance for a deterministic iteration.
	byDesc := make(map[string]*descRecords)
	var order []string
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" {
			continue
		}
		fields := strings.Split(line, "\t")
		expr := fields[0]
		rec, ok := byDesc[expr]
		if !ok {
			rec = &descRecords{}
			byDesc[expr] = rec
			order = append(order, expr)
		}

		switch fields[1] {
		case "PARSEERR":
			t.Errorf("rust could not parse corpus "+
				"descriptor %s: %s", expr, fields[2])

		case "STR":
			rec.str = fields[2]

		case "MPLEN":
			rec.mplen = fields[2]

		case "TYPE":
			rec.typ = fields[2]

		case "MWEIGHT":
			rec.mweight = fields[2]

		case "LIFT":
			rec.lift = fields[2]

		case "PLAN":
			rec.plan = fields[2:]

		case "KEY":
			rec.keys = append(rec.keys, fields[2])

		case "ADDR":
			rec.addr = append(rec.addr, fields[2:])

		case "SCODE":
			rec.scode = append(rec.scode, fields[2:])
		}
	}
	require.NoError(t, scanner.Err())
	require.NotEmpty(t, order)

	for _, expr := range order {
		expr := expr
		rec := byDesc[expr]
		t.Run(expr, func(t *testing.T) {
			t.Parallel()
			checkDescriptor(t, expr, rec)
		})
	}
}

// checkDescriptor parses one descriptor in Go and asserts all of its computed
// properties match the rust reference records.
func checkDescriptor(t *testing.T, expr string, rec *descRecords) {
	d, err := NewDescriptor(expr)
	require.NoErrorf(t, err, "go could not parse %s", expr)

	require.Equal(t, rec.str, d.String(), "canonical string")
	require.Equal(t, rec.mplen, strconv.Itoa(d.MultipathLen()),
		"multipath length")
	require.Equal(t, rec.typ, string(d.DescType()), "descriptor type")
	require.Equal(t, rec.keys, d.Keys(), "keys")

	// Maximum satisfaction weight. Rust emits "ERR:<msg>" when the
	// descriptor cannot be satisfied.
	weight, weightErr := d.MaxWeightToSatisfy()
	if strings.HasPrefix(rec.mweight, "ERR:") {
		require.Errorf(t, weightErr,
			"expected weight error for %s", expr)
	} else {
		require.NoErrorf(t, weightErr, "weight for %s", expr)
		require.Equalf(t, rec.mweight, strconv.FormatUint(weight, 10),
			"max weight to satisfy for %s", expr)
	}

	// Lifted semantic policy, compared in its canonical display form.
	policy, liftErr := d.Lift()
	if strings.HasPrefix(rec.lift, "ERR:") {
		require.Errorf(t, liftErr, "expected lift error for %s", expr)
	} else {
		require.NoErrorf(t, liftErr, "lift for %s", expr)
		require.Equalf(t, rec.lift, policy.String(),
			"lifted policy for %s", expr)
	}

	// Plan weights, computed with every signature and timelock available so
	// the planner picks the cheapest spending path.
	relLock, absLock := uint32(65535), uint32(499999999)
	plan, planErr := d.PlanAt(0, 0, Assets{
		LookupEcdsaSig: func(string) bool { return true },
		LookupTapKeySpendSig: func(string) (uint32, bool) {
			return 64, true
		},
		LookupTapLeafScriptSig: func(string, string) (uint32, bool) {
			return 64, true
		},
		RelativeLocktime: &relLock,
		AbsoluteLocktime: &absLock,
	})
	if len(rec.plan) == 1 && rec.plan[0] == "ERR" {
		require.Errorf(t, planErr, "expected plan error for %s", expr)
	} else {
		require.NoErrorf(t, planErr, "plan for %s", expr)
		require.Lenf(t, rec.plan, 3, "plan record for %s", expr)
		require.Equalf(t, rec.plan[0], strconv.FormatUint(
			plan.SatisfactionWeight(), 10),
			"plan satisfaction weight for %s", expr)
		require.Equalf(t, rec.plan[1], strconv.FormatUint(
			plan.ScriptSigSize(), 10),
			"plan scriptsig size for %s", expr)
		require.Equalf(t, rec.plan[2], strconv.FormatUint(
			plan.WitnessSize(), 10),
			"plan witness size for %s", expr)
	}

	for _, a := range rec.addr {
		// a = [mp, idx, net, value] (value may be "ERR:..."), or
		//     [mp, idx, "ERR", msg] for a derivation error.
		mp := mustUint32(t, a[0])
		idx := mustUint32(t, a[1])
		net, value := a[2], a[3]

		if net == "ERR" {
			_, err := d.AddressAt(&chaincfg.MainNetParams, mp, idx)
			require.Errorf(t, err, "expected address derivation "+
				"error for %s at (%d,%d)", expr, mp, idx)
			continue
		}

		params := networkParams(t, net)
		require.NotNilf(t, params, "unknown network %q", net)
		got, err := d.AddressAt(params, mp, idx)
		if strings.HasPrefix(value, "ERR:") {
			require.Errorf(t, err, "expected address error for %s "+
				"at (%d,%d,%s)", expr, mp, idx, net)
			continue
		}
		require.NoErrorf(t, err, "address for %s at (%d,%d,%s)", expr,
			mp, idx, net)
		require.Equalf(t, value, got, "address for %s at (%d,%d,%s)",
			expr, mp, idx, net)
	}

	for _, s := range rec.scode {
		// s = [mp, idx, value] where value is hex or "ERR:...".
		mp := mustUint32(t, s[0])
		idx := mustUint32(t, s[1])
		value := s[2]

		got, err := d.ScriptCodeAt(mp, idx)
		if strings.HasPrefix(value, "ERR:") {
			require.Errorf(t, err, "expected script code error "+
				"for %s at (%d,%d)", expr, mp, idx)
			continue
		}
		require.NoErrorf(t, err, "script code for %s at (%d,%d)", expr,
			mp, idx)
		require.Equalf(t, value, hex.EncodeToString(got), "script "+
			"code for %s at (%d,%d)", expr, mp, idx)
	}
}

// mustUint32 parses a base-10 uint32 or fails the test.
func mustUint32(t *testing.T, s string) uint32 {
	n, err := strconv.ParseUint(s, 10, 32)
	require.NoError(t, err)
	return uint32(n)
}
