package descriptors

import (
	"bufio"
	"encoding/hex"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/btcsuite/btcd/chaincfg/v2"
	"github.com/stretchr/testify/require"
)

// descRecords holds the rust-generated reference records for one descriptor.
type descRecords struct {
	str     string
	mplen   string
	typ     string
	mweight string
	lift    string
	plan    []string
	keys    []string
	addr    [][]string
	scode   [][]string
}

// TestDescriptorDifferential compares this Go implementation against the
// rust-miniscript reference for every descriptor in the corpus, on the
// canonical string, multipath length, type, keys, and every derived address and
// script code. The reference is generated by a patch on top of rust-miniscript
// to allow extraction of test vectors, into testdata/descriptors_from_rust.tsv.
func TestDescriptorDifferential(t *testing.T) {
	t.Parallel()

	f, err := os.Open("testdata/descriptors_from_rust.tsv")
	require.NoError(t, err)
	defer func() {
		require.NoError(t, f.Close())
	}()

	// Read and group the reference records by descriptor, preserving order
	// of appearance for a deterministic iteration.
	byDesc := make(map[string]*descRecords)
	var order []string
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" {
			continue
		}
		fields := strings.Split(line, "\t")
		require.GreaterOrEqualf(
			t, len(fields), 3, "malformed row: %s", line,
		)
		expr := fields[0]
		rec, ok := byDesc[expr]
		if !ok {
			rec = &descRecords{}
			byDesc[expr] = rec
			order = append(order, expr)
		}

		switch fields[1] {
		case "PARSEERR":
			require.FailNowf(
				t, "rust rejected corpus descriptor", "%s: %s",
				expr, fields[2],
			)

		case "STR":
			rec.str = fields[2]

		case "MPLEN":
			rec.mplen = fields[2]

		case "TYPE":
			rec.typ = fields[2]

		case "MWEIGHT":
			rec.mweight = fields[2]

		case "LIFT":
			rec.lift = fields[2]

		case "PLAN":
			rec.plan = fields[2:]

		case "KEY":
			rec.keys = append(rec.keys, fields[2])

		case "ADDR":
			rec.addr = append(rec.addr, fields[2:])

		case "SCODE":
			rec.scode = append(rec.scode, fields[2:])
		}
	}
	require.NoError(t, scanner.Err())
	require.NotEmpty(t, order)

	for _, expr := range order {
		rec := byDesc[expr]
		t.Run(expr, func(t *testing.T) {
			t.Parallel()
			checkDescriptor(t, expr, rec)
		})
	}
}

// planScriptSigAdjustment returns how much larger the scriptSig this package
// reports for a plan is than the one rust-miniscript v13 reports, which is only
// non-zero for P2SH descriptors and has two independent reasons:
//
//   - for a P2SH-wrapped segwit output, rust reports the raw length of the
//     scriptSig, while Plan.ScriptSigSize is documented as the size of the
//     serialized field, i.e. one byte more for the var-int that prefixes it. (A
//     plan with an empty scriptSig reports 1 in both implementations, so rust is
//     only self-consistent for that case.) Pending upstream:
//     rust-bitcoin/rust-miniscript#1045 adds the byte.
//   - for a legacy P2SH, rust does not count the redeem script at all, because
//     its plan hands it to the PSBT input as a separate field instead of
//     producing scriptSig bytes. Plan.Satisfy does produce them, so its size has
//     to cover the redeem script push. Note rust's own max_weight_to_satisfy
//     counts the redeem script too, i.e. its two APIs disagree with each other.
//     No byte is added for the var-int here: rust sizes a legacy scriptSig like
//     a witness, whose element count takes the byte our convention spends on the
//     var-int prefix.
func planScriptSigAdjustment(t *testing.T, d *Descriptor) uint64 {
	t.Helper()

	switch d.DescType() {
	case DescTypeShWpkh, DescTypeShWsh:
		return 1

	case DescTypeSh:
		// The redeem script of a legacy P2SH is its script code.
		redeem, err := d.ScriptCodeAt(0, 0)
		require.NoError(t, err)

		return uint64(pushOpcodeSize(len(redeem)) + len(redeem))

	default:
		return 0
	}
}

// planWitnessSizeAdjustment returns how much larger the witness this package
// reports for a plan is than the one rust-miniscript v13 reports, which is only
// non-zero for the two P2WSH descriptor types.
//
// A P2WSH spend has to reveal its witness script as the last witness element
// (BIP141), and rust's Plan::satisfy does append it, but its witness_size and
// satisfaction_weight leave those bytes out, i.e. its own two APIs disagree
// about the same witness. Both cover the full witness here, so the reference
// value is short by the serialized witness script.
//
// The element count var-int is one byte on both sides: no descriptor of the
// corpus has a satisfaction of 252 or more elements, which is where the count
// would need three bytes.
//
// Pending upstream: rust-bitcoin/rust-miniscript#1045 counts the bytes, so this
// adjustment, and the wrapped-segwit half of planScriptSigAdjustment, go away
// once the corpus is regenerated with a rust that has the fix. The legacy P2SH
// half of that one stays, since rust keeps the redeem script out of its plan on
// purpose.
func planWitnessSizeAdjustment(t *testing.T, d *Descriptor) uint64 {
	t.Helper()

	switch d.DescType() {
	case DescTypeWsh, DescTypeShWsh:
		// The witness script of a P2WSH output is its script code.
		script, err := d.ScriptCodeAt(0, 0)
		require.NoError(t, err)

		return uint64(varintLen(uint64(len(script))) + len(script))

	default:
		return 0
	}
}

// mustUint64 parses a decimal reference value.
func mustUint64(t *testing.T, s string) uint64 {
	t.Helper()

	value, err := strconv.ParseUint(s, 10, 64)
	require.NoErrorf(t, err, "parsing %q", s)

	return value
}

// checkDescriptor parses one descriptor in Go and asserts all of its computed
// properties match the rust reference records.
func checkDescriptor(t *testing.T, expr string, rec *descRecords) {
	t.Helper()

	d, err := NewDescriptor(expr)
	require.NoErrorf(t, err, "go could not parse %s", expr)

	require.Equal(t, rec.str, d.String(), "canonical string")
	require.Equal(
		t, rec.mplen, strconv.Itoa(d.MultipathLen()),
		"multipath length",
	)
	require.Equal(t, rec.typ, string(d.DescType()), "descriptor type")
	require.Equal(t, rec.keys, d.Keys(), "keys")

	// Maximum satisfaction weight. Rust emits "ERR:<msg>" when the
	// descriptor cannot be satisfied.
	weight, weightErr := d.MaxWeightToSatisfy()
	if strings.HasPrefix(rec.mweight, "ERR:") {
		require.Errorf(t, weightErr,
			"expected weight error for %s", expr)
	} else {
		require.NoErrorf(t, weightErr, "weight for %s", expr)
		require.Equalf(
			t, rec.mweight, strconv.FormatUint(weight, 10),
			"max weight to satisfy for %s", expr,
		)
	}

	// Lifted semantic policy, compared in its canonical display form.
	policy, liftErr := d.Lift()
	if strings.HasPrefix(rec.lift, "ERR:") {
		require.Errorf(t, liftErr, "expected lift error for %s", expr)
	} else {
		require.NoErrorf(t, liftErr, "lift for %s", expr)
		require.Equalf(
			t, rec.lift, policy.String(), "lifted policy for %s",
			expr,
		)
	}

	// Plan weights, computed with every signature and timelock available so
	// the planner picks the cheapest spending path. The transaction the
	// plans are for is a version 2 one with a non-final input sequence, so
	// both kinds of locktime are enforced for it.
	version := int32(2)
	sequence, lockTime := uint32(65535), uint32(499999999)
	plan, planErr := d.PlanAt(0, 0, Assets{
		LookupEcdsaSig: func(string) bool { return true },
		LookupTapKeySpendSig: func(string) (uint32, bool) {
			return 64, true
		},
		LookupTapLeafScriptSig: func(string, string) (uint32, bool) {
			return 64, true
		},
		TxVersion:       &version,
		TxLockTime:      &lockTime,
		TxInputSequence: &sequence,
	})
	if len(rec.plan) == 1 && rec.plan[0] == "ERR" {
		require.Errorf(t, planErr, "expected plan error for %s", expr)
	} else {
		require.NoErrorf(t, planErr, "plan for %s", expr)
		require.Lenf(t, rec.plan, 3, "plan record for %s", expr)

		// The scriptSig and witness accounting of a plan intentionally
		// differs from rust-miniscript v13 for the P2SH and P2WSH
		// descriptor types, see planScriptSigAdjustment and
		// planWitnessSizeAdjustment.
		adjust := planScriptSigAdjustment(t, d)
		witnessAdjust := planWitnessSizeAdjustment(t, d)
		wantScriptSig := mustUint64(t, rec.plan[1]) + adjust
		wantWitness := mustUint64(t, rec.plan[2]) + witnessAdjust
		wantWeight := mustUint64(t, rec.plan[0]) + 4*adjust +
			witnessAdjust

		require.Equalf(
			t, wantWeight, plan.SatisfactionWeight(),
			"plan satisfaction weight for %s", expr,
		)
		require.Equalf(
			t, wantScriptSig, plan.ScriptSigSize(),
			"plan scriptsig size for %s", expr,
		)
		require.Equalf(
			t, wantWitness, plan.WitnessSize(),
			"plan witness size for %s", expr,
		)
	}

	for _, a := range rec.addr {
		// a = [mp, idx, net, value] (value may be "ERR:..."), or
		//     [mp, idx, "ERR", msg] for a derivation error.
		mp := mustUint32(t, a[0])
		idx := mustUint32(t, a[1])
		net, value := a[2], a[3]

		if net == "ERR" {
			_, err := d.AddressAt(&chaincfg.MainNetParams, mp, idx)
			require.Errorf(t, err, "expected address derivation "+
				"error for %s at (%d,%d)", expr, mp, idx)
			continue
		}

		params := networkParams(t, net)
		require.NotNilf(t, params, "unknown network %q", net)
		got, err := d.AddressAt(params, mp, idx)
		if strings.HasPrefix(value, "ERR:") {
			require.Errorf(t, err, "expected address error for %s "+
				"at (%d,%d,%s)", expr, mp, idx, net)
			continue
		}
		require.NoErrorf(t, err, "address for %s at (%d,%d,%s)", expr,
			mp, idx, net)
		require.Equalf(
			t, value, got, "address for %s at (%d,%d,%s)", expr, mp,
			idx, net,
		)
	}

	for _, s := range rec.scode {
		// s = [mp, idx, value] where value is hex or "ERR:...".
		mp := mustUint32(t, s[0])
		idx := mustUint32(t, s[1])
		value := s[2]

		got, err := d.ScriptCodeAt(mp, idx)
		if strings.HasPrefix(value, "ERR:") {
			require.Errorf(t, err, "expected script code error "+
				"for %s at (%d,%d)", expr, mp, idx)
			continue
		}
		require.NoErrorf(t, err, "script code for %s at (%d,%d)", expr,
			mp, idx)
		require.Equalf(
			t, value, hex.EncodeToString(got),
			"script code for %s at (%d,%d)", expr, mp, idx,
		)
	}
}

// mustUint32 parses a base-10 uint32 or fails the test.
func mustUint32(t *testing.T, s string) uint32 {
	t.Helper()

	n, err := strconv.ParseUint(s, 10, 32)
	require.NoError(t, err)
	return uint32(n)
}
